import React from 'react';
/*const intro= `A motivated programmer with knowledge in varieties of programming languages. I'm currently looking for a job in software development. I am a dedicated, outgoing and a team player.
`;*/
//const intro2="Are you looking for a trainee with? * Knowledge of the latest technology in Computer Science? * Excellent written and oral communication skills? * A passion to learn and to increase his skills? If so, then you need look no further. You will see from my enclosed resume that I meet all of these qualifications and more. Hello, I am srijan Chapagain. I have been living in Finland for 5 years now. I speak little Finnish and now also learning Swedish. I am a computer enthusiast. I like to learn new programming language and work in mainly backend programming. I got the motivation for programming when I was in my A-Levels and had to make a software for a real company in C# and Vb.net. I made an inventory system to store store's data, search from the records, create data profiles and so on. Since then I am extremely motivated to put everything to work in a company to develop softwares. During my bachelor's degree at Centria UAS in Kokkola, I was fortunate to learn Android studio, Java, QT, C++, Object oriented programming and modelling. During my bachelor’s thesis, I have explored the areas of app development in augmented reality with Vuforia for Unity3D . I am continuing my studies on master’s degree at Åbo Akademi.I am very interested in becoming a part of your team. Your facility would gain an individual who is dependable, motivated, and personable. My many experiences ensure that I am an individual who knows how to accomplish tasks and work in a team dynamic. I would appreciate the opportunity to discuss my credentials with you at a mutually convenient time. If you have any questions or would like more information about my qualifications, please feel free to call me at 04578770641 or email me at chapssrijan@gmail.com. Thank you for your consideration.Thank you for taking the time to review my resume. I look forward to talking with you. "

const intro3=[<p>Are you looking for a trainee with?</p>,<li> Knowledge of the latest technology in Computer Science?</li>,<li>Excellent written and oral communication skills?</li>,<li> A passion to learn and to increase his skills?</li>,
<p>If so, then you need look no further. You will see from my enclosed resume that I meet all of these qualifications and more.</p>,
<p>Hello, I am srijan Chapagain. I have been living in Finland for 5 years now. I speak little Finnish and now also learning Swedish. I am a computer enthusiast. I like to learn new programming language and work in mainly backend programming. I got the motivation for programming when I was in my A-Levels and had to make a software for a real company in C# and Vb.net. I made an inventory system to store store's data, search from the records, create data profiles and so on. Since then I am extremely motivated to put everything to work in a company to develop softwares. During my bachelor's degree at Centria UAS in Kokkola, I was fortunate to learn Android studio, Java, QT, C++, Object oriented programming and modelling. During my bachelor’s thesis, I have explored the areas of app development in augmented reality with Vuforia for Unity3D . I am continuing my studies on master’s degree at Åbo Akademi</p>,
<p>I am very interested in becoming a part of your team. Your facility would gain an individual who is dependable, motivated, and personable. My many experiences ensure that I am an individual who knows how to accomplish tasks and work in a team dynamic.</p>,
<p>I would appreciate the opportunity to discuss my credentials with you at a mutually convenient time. If you have any questions or would like more information about my qualifications, please feel free to call me at 04578770641 or email me at chapssrijan@gmail.com. Thank you for your consideration</p>,
<p>Thank you for taking the time to review my resume. I look forward to talking with you. </p>,
<span style={{ color: "#C70039" }}>Sincerely, </span>,
<p style={{ color: "#C70039" }}>Srijan Chapagain</p> ]
export default intro3 ;